# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_doctor', '0002_family_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_doctor.Doctor')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_doctor.Family')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_doctor.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='family_doctor',
            name='time',
        ),
    ]
